### ISSUE TITLE
Add sha256sums.txt with Releases

### ISSUE THREAD

**Issue by atomlab** [solana-labs/solana#13593]
#### Problem

I use ansible to automation solana deploy and would be very useful to check sha256sum of release before download.

Example
```
- name: download solana archive
  get_url:
    url: "https://github.com/solana-labs/solana/releases/download/v{{ solana_release }}/solana-release-x86_64-unknown-linux-gnu.tar.bz2"
    checksum: "sha256:https://github.com/solana-labs/solana/releases/download/v{{ solana_release }}/sha256sums.txt"
    dest: /var/cache/

- name: ensure solana release have unpacked
  unarchive:
    src: "/var/cache/solana-release-x86_64-unknown-linux-gnu.tar.bz2"
    dest: "/usr/local/bin/"
    mode: 0755
    owner: solana
    group: solana
    copy: no
    extra_opts:
    - --strip=2
    - --no-anchored
``` 

#### Proposed Solution

Upload sha256sums.txt with each release. 

```
# Example
https://github.com/prometheus/prometheus/releases/download/v2.22.1/sha256sums.txt
```
