### ISSUE TITLE
`process_transaction` hangs after `warp_to_slot` and `get_new_blockhash` in `solana_program_test`

### ISSUE THREAD

**Issue by ruuda** [solana-labs/solana#18201]
I stumbled upon an interaction between `ProgramTestContext::warp_to_slot` and `ProgramTestBanksClientExt::get_new_blockhash`, that makes `process_transaction` hang.

Consider the following minimal project.

`Cargo.toml`:
```toml
[package]
name = "repro"
version = "0.1.0"
authors = []
edition = "2018"

[features]
test-bpf = []

[dependencies]
solana-program = "1.7.3"

[dev-dependencies]
solana-program-test = "1.7.3"
solana-sdk = "1.7.3"
tokio = "1.0"

[lib]
crate-type = ["cdylib", "lib"]
```

`src/lib.rs`:
```rust
use solana_program::{
    pubkey::Pubkey,
    account_info::AccountInfo,
    entrypoint::ProgramResult,
};

pub fn process(_: &Pubkey, _: &[AccountInfo], _: &[u8]) -> ProgramResult {
    Ok(())
}
```

`tests/repro.rs`:
```rust
#![cfg(feature = "test-bpf")]

use solana_program;
use solana_program::pubkey::Pubkey;
use solana_program_test::{ProgramTest, ProgramTestBanksClientExt, processor};
use solana_sdk::signature::Signer;
use solana_sdk::transaction::Transaction;

solana_program::declare_id!("3kEkdGe68DuTKg6FhVrLPZ3Wm8EcUPCPjhCeu8WrGDoc");

#[tokio::test]
async fn test_repro() {
    let program_test = ProgramTest::new("repro", id(), processor!(repro::process));
    let mut context = program_test.start_with_context().await;

    // Option 1: Remove the next statement, and the tests pass.
    context.warp_to_slot(3).unwrap();

    let new_blockhash = context
        .banks_client
        .get_new_blockhash(&context.last_blockhash)
        .await
        .unwrap()
        .0;

    let mut tx = Transaction::new_with_payer(&[], Some(&context.payer.pubkey()));

    // Option 2: Sign with context.last_blockhash instead, and the tests pass.
    tx.sign(&[&context.payer], new_blockhash);

    // This hangs for a minute, and then fails with
    // IoError(Custom { kind: TimedOut, error: "Client dropped expired request." })
    context.banks_client.process_transaction(tx).await.unwrap();
}
```

As presented here, the test fails. By either removing the `warp_to_slot`, *or* signing with the old block hash, the tests pass.

Is this a bug, or am I using the test context incorrectly? How can I warp to a new slot, and then in that slot still get fresh block hashes so I can process two transactions that are not distinct by value, but which should both execute nonetheless?
