### ISSUE TITLE
Docker image broken for 1.7.15

### ISSUE THREAD

**Issue by kevinheavey** [solana-labs/solana#20692]
#### Problem

Running the Docker image for v1.7.15 fails with:

`/usr/bin/solana-run.sh: line 66: ./fetch-spl.sh: No such file or directory`

I'm using docker-compose; here's my docker-compose.yml:

```
version: '3'
services:
  localnet:
    image: "solanalabs/solana:v1.7.15"
    ports:
      - "8899:8899"
      - "8900:8900"
      - "9900:9900"
```
