### ISSUE TITLE
Error reading keypair from STDIN for spk-token create-token command

### ISSUE THREAD

**Issue by sdeoras** [solana-labs/solana#21811]
#### Problem
One of the ways to support keypair encryption on disk via cloud services such as Google KMS is to build a tool that prints out JSON formatted keypair data and passes it to solana cli tools via STDIN. While exploring this path I observed that it worked as expected on some commands but failed on others.

Steps to repro:
Change the keypair_path to `stdin:` as follows:
```yaml
json_rpc_url: "http://localhost:8899"
websocket_url: ""
keypair_path: "stdin:"
address_labels:
  "11111111111111111111111111111111": System Program
commitment: confirmed
```
Confirm that keypair input via STDIN is working:
```
└─ $ ▶ cat .config/solana/id.json | solana balance 
99.9970568 SOL
```
Try creating a new SPL token. It fails here:
```
└─ $ ▶ cat ~/.config/solana/id.json | spl-token create-token
error: EOF while parsing a value at line 1 column 0
```

Change the keypair_path in config to point to the keypair file instead of `stdin:` 
```yaml
json_rpc_url: "http://localhost:8899"
websocket_url: ""
keypair_path: "/home/username/.config/solana/id.json"
address_labels:
  "11111111111111111111111111111111": System Program
commitment: confirmed
```

Try creating spl token and it should go through
```
└─ $ ▶ spl-token create-token
Creating token 7iXjPZni3fGFzfojvfC6sxYHhtrJrXcH2zFpGThU7tg

Signature: 43UZiVQ5iCdT2uWPuKM6bjVK1s3a6KfLjaTyTxVBWLRivy7XYwA7wjUyp2HvQmVztcREXABtPL4CRnCeBbs6j7xL

```

It seems there is a bug in how data received on STDIN is intercepted by spl-token command. In particular, I would have expected the keypair input to be sufficient when passed via STDIN.
