### ISSUE TITLE
Cannot parse config via `solana-cli-config`

### ISSUE THREAD

**Issue by awkure** [solana-labs/solana#22424]
#### Problem

Currently, when installing solana on my mac machine via `sh -c "$(curl -sSfL https://release.solana.com/v1.9.4/install)"` it generates the following config file 

```yaml
---
json_rpc_url: "http://api.devnet.solana.com"
update_manifest_pubkey:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
current_update_manifest: ~
update_poll_secs: 3600
explicit_release:
  Semver: 1.9.4
releases_dir: /Users/awkure/.local/share/solana/install/releases
active_release_dir: /Users/awkure/.local/share/solana/install/active_release
```

It fails to parse with 

```
"invalid type: integer `159`, expected a map\", Some(Pos { marker: Marker { index: 13, line: 1, col: 13 }, path: \".[3]\" }))" }
```

and also missing `keypair_path` key.

I did `solana-keygen pubkey` and checked that the balance is non-zero and still the problem persists.
