### ISSUE TITLE
whitelist for QUIC connections to apply the stake of the local validator

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#26407]
#### Problem

The validator may want to prioritize QUIC traffic from a known whitelist of sources and apply its own stake to those transactions.

#### Proposed Solution

Add an option for a whitelist to the validator to always accept quic connections from and apply its stake weighted priority to.

**Comment by janlegner** [comment]
@sakridge With normal stake weighted connections the weights are updated automatically based on the status of the network. What would be a good strategy for managing updates of the suggested whitelist? (E.g. if you want to add IP to whitelist, remove IP, change its stake, ...)
Maybe a file with a configuration that could be automatically polled from the local file system or URL, so validators would not need to restart the `solana-validator`? What do you think?

```yaml
auto_refresh: true/false
quic_stake_override:
  - ip: xxx.xxx.xxx.xxx
    stake: 123456789
  - ...
```
