### ISSUE TITLE
Solana program deploy fails with Error: ELF error: ELF error: Incompatible ELF: wrong machine

### ISSUE THREAD

**Issue by 0xcrust** [solana-labs/solana#29423]
Building the program with `cargo build-sbf` works, but trying to deploy the resulting so file with `solana program deploy <path>` fails with the error shown above.

This is the case for both localnet and devnet. Deploying with the Solana Playground also fails with the same error.

A peek at my Cargo.toml:

```toml

[package]
name = "program"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "=1.14.4"
thiserror = "1.0.24"
arrayref = "0.3.6"

[dev-dependencies]
solana-logger = "=1.14.4"
solana-program-test = "=1.14.4"
solana-sdk = "=1.14.4"
solana-validator = "=1.14.4"

[lib]
crate-type = ["cdylib", "lib"]

```

I'm running the Solana-cli 1.4.10 on Ubuntu 22.04.
