### ISSUE TITLE
Very first tutorial does not work. All new users will fail if they don't understand how to debug your codebase on an intimate level.

### ISSUE THREAD

**Issue by FrackinFamous** [solana-labs/solana#34991]
#### Problem
This is broken:
https://solana.com/developers/guides/getstarted/local-rust-hello-world

If you start with a fresh linux system and run this tutorial you will fail. 

#### Proposed Solution
A team member recording a video going through this step by step and proving it works.

**Comment by moopa** [comment]
I've just arrived here looking for a solution to this.
Running with `solana-test-validator` which appears to be running fine, I get the following error using `cargo build-bpf`: 

```
Error: Function _ZN112_$LT$solana_program..instruction..InstructionError$u20$as$u20$solana_frozen_abi..abi_example..AbiEnumVisitor$GT$13visit_for_abi17h8d5db8dd5086d5f8E Stack offset of 4584 exceeded max offset of 4096 by 488 bytes, please minimize large stack variables
```

**System info:**
Apple Arm (M1)
solana-cli 1.18.0
stable-aarch64-apple-darwin (default)
rustc 1.75.0 (82e1608df 2023-12-21)

Some insights would be appreciated. I saw a Stack offset error on another issue where they suspected it was the test validator? Possibly a red herring.

**Comment by vebodev** [comment]
I met the same problem after upgrading to 1.18.0. After struggling for a couple of hours, I downgraded to 1.17.17 finally, and it works again without the `Stack exceed max capacity` error.

```sh
# download Solana tool v1.17.17
sh -c "$(curl -sSfL https://release.solana.com/v1.17.17/install)"
# force to redownload rust toolchains 
cargo-build-sbf --force-tools-install
```

And, all the dependencies should be at "1.17.17" as well.
```toml
[dependencies]
borsh = { version = "0.10.3" }
borsh-derive = { version = "0.10.3" }
chrono = "0.4.33"
solana-program = "=1.17.17"
spl-token = "4.0.0"

[dev-dependencies]
solana-program-test = "1.17.17"
solana-sdk = "1.17.17"
```
Finally, I succeeded. :smile:

```sh
❯ cargo build-sbf
    Finished release [optimized] target(s) in 0.46s
```
