### ISSUE TITLE
docs.rs request: only build on one target

### ISSUE THREAD

**Issue by jyn514** [solana-labs/solana#9543]
#### Problem

When solana-labs publishes a new version, it takes docs.rs a while to build all the solana crates, which delays the time for the documentation to be published. For example, even though solana published `1.0.18` two hours ago, there are still [11 crates waiting to be built](https://docs.rs/releases/queue).

#### Proposed Solution

Most of the build time comes from docs.rs trying to build `solana-*` crates for each of the 5 tier one targets. docs.rs has a way to opt-in to only building one target: https://blog.rust-lang.org/2020/03/15/docs-rs-opt-into-fewer-targets.html. This would reduce the build times by a factor of 5 (and also speed up the docs.rs queue for other crates).

```toml
[package.metadata.docs.rs]
# This sets the default target to `x86_64-unknown-linux-gnu`
# and only builds that target
targets = ["x86_64-unknown-linux-gnu"]
```

Note that since the build currently only succeeds on `x86_64-unknown-linux-gnu` and `i686-unknown-linux-gnu`, the only effect from an end-user's perspective will be to remove the x32 docs. If you would like to keep the x32 docs you could use `targets = ["x86_64-unknown-linux-gnu", "i686-unknown-linux-gnu"]` instead, which will still have a 2.5x speedup compared to before.

Disclosure: I am a maintainer of docs.rs.
